### ISSUE TITLE
C++ version

### ISSUE THREAD

**Issue by claremacrae** [emilybache/Theatrical-Players-Refactoring-Kata#3]
Hi Emily

Just to let you know I'm starting on a C++ version - please do say if anyone else has already started (that you know of)

Clare

**Comment by claremacrae** [comment]
I'm thinking of saying this in the readme... (doctest is similar to Catch2, but doctest is designed for faster compile times)

The tests use the following header-only projects, which are in the `third_party` sub-directory:

| Project | Licence |
| --- | --- |
| [doctest test framework](https://github.com/onqtam/doctest) | [MIT](https://github.com/onqtam/doctest/blob/master/LICENSE.txt) |
| [ApprovalTests.cpp](https://github.com/approvals/ApprovalTests.cpp) | [Apache 2.0](https://github.com/approvals/ApprovalTests.cpp/blob/master/LICENSE) |
| [JSON for Modern C++](https://github.com/nlohmann/json) | [MIT](https://github.com/nlohmann/json/blob/develop/LICENSE.MIT) |

**Comment by emilybache** [comment]
Very happy to see you do this C++ version. Adding license information to a README in the C++ folder seems like a good idea too.
