### ISSUE TITLE
Update Go version

### ISSUE THREAD

**Issue by iwodder** [emilybache/Theatrical-Players-Refactoring-Kata#39]
Hi @emilybache ,

I was working through the Go variant of the kata and noticed it hadn't been updated in sometime. I was wondering if you'd be open to letting me update it?

I was thinking about making the following changes:

1. Update Go to version 1.22, so people could take advantage of generics and other language updates.
2. Replace the custom `verify` method used in the approval test to instead leverage `approvals/go-approval-test`. Essentially, it's just following up on the conversation you had with the original author of the Go variant.

Let me know what you think.

Also, thanks for taking the time to put this together. I did the kata while following along with the book and found it interesting.

**Comment by emilybache** [comment]
Those sound like very sensible updates, thanks for suggesting them. Would you like to send me a pull request?

**Comment by iwodder** [comment]
Of course, I went ahead and submitted a PR a few minutes ago.

**Comment by emilybache** [comment]
Thanks!
