### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by ardalis** [emilybache/Theatrical-Players-Refactoring-Kata#9]
Any chance this kata could have specific instructions added in the home README file? Trying to use it but it's a bit more open-ended than most katas.

**Comment by cadichris** [comment]
Hi @ardalis.
You can find instructions in the book mentionned by the README : ['Refactoring' by Martin Fowler, 2nd Edition](https://www.thoughtworks.com/books/refactoring2)

The context and instructions are in the first chapter, and this chapter **is available for free**.
At the time of writing, PDF is available at : https://files.thoughtworks.com/pdfs/Refactoring2-free-chapter.pdf

You can search for

> _In this case, I have a couple of changesthat  the  users  would  like  to  make.  First,they want a statement printed in HTML._

This will point you to the content you might be looking for.

**Comment by codecop** [comment]
Could you provide a PR with the link to the instructions added to the Readme please.

**Comment by cadichris** [comment]
@codecop Well the README of the repo we're on already seems pretty precise to me :

![image](https://user-images.githubusercontent.com/24898521/100605469-3fea3280-3308-11eb-8069-05bb7cd3c484.png)
